default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: zachet
  encoding: unicode
  host: localhost
  pool: 5
  username: postgres
  password: 1111


test:
  <<: *default
  database: zachet_test
  encoding: unicode
  host: localhost
  pool: 5
  username: postgres
  password: 1111


production:
  <<: *default
  encoding: unicode
  database: zachet_production
  host: localhost
  pool: 5
  username: postgres
  password: <%= ENV["testsecond_Password"] %>